'use client'
import './globals.css';
import Footer from '@/common/components/Footer';
import Header from '@/common/components/Header';
import {Jost} from 'next/font/google';

const jost = Jost({subsets: ['latin'], display: 'swap'});

export const metadata = {
  title: 'Ayahay',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={jost.className}>
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
