import './globals.css';
import Footer from '@/common/components/Footer';
import Header from '@/common/components/Header';

export const metadata = {
  title: 'Ayahay',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
