import './globals.css'
import Footer from "@/common/components/Footer";
import Header from "@/common/components/Header";
import {Layout} from "antd";

export const metadata = {
  title: 'Ayahay',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
